language: node_js
node_js:
    - "5.11"
    - "6"
    - "6.1"
    - "6.2" 
before_install:
    - sudo add-apt-repository ppa:vase/ppa -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq etcd
    - nohup etcd &
